// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Entry struct {
	Topics      []string `json:"Topics"`
	Homnum      string   `json:"Homnum"`
	Freqs       []string `json:"Freqs"`
	SpeakerURLs []string `json:"SpeakerURLs"`
	Hyphenation string   `json:"Hyphenation"`
	Pron        string   `json:"Pron"`
	Poses       []string `json:"Poses"`
	Senses      []*Sense `json:"Senses"`
}

type Example struct {
	AudioURL string `json:"AudioURL"`
	Text     string `json:"Text"`
}

type Sense struct {
	SignPost   string     `json:"SignPost"`
	Definition string     `json:"Definition"`
	Gram       string     `json:"Gram"`
	Examples   []*Example `json:"Examples"`
}

type Word struct {
	Name    string   `json:"Name"`
	Entries []*Entry `json:"Entries"`
}
